description: >
  This is the executor that uses the container image for the OpsLevel CLI.

docker:
  - image: 'public.ecr.aws/opslevel/cli:<<parameters.tag>>'

parameters:
  tag:
    default: 'v2024.3.15'
    description: >
      Pick a release (minimum supported version is v2024.3.15):
      https://github.com/OpsLevel/cli/releases
    type: string
