name: "Release"

permissions:
  contents: write

on:
  push:
    branches: [ main ]


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Report Release To OpsLevel
        uses: opslevel/report-deploy-github-action@v3.0.0
        with:
          integration_url: ${{ secrets.DEPLOY_INTEGRATION_URL }}
          service: "opslevel-orb"
